### ISSUE TITLE
Please add a LICENSE.txt file

### ISSUE THREAD

**Issue by jrn** [typetools/annotation-tools#108]
When looking over annotation-tools, I had trouble finding its license. Is it under the same BSD-style license as asm? A file like https://github.com/typetools/checker-framework/blob/master/LICENSE.txt would have helped me figure that out.

I started writing the following LICENSE.txt file for a pull request but stopped because I wasn't sure what the intended license is. (I don't mind if the package doesn't document the licenses of its dependencies --- I'm fine with having to chase those down.)

Thanks,
Jonathan

The Annotation Tools have the following license:

Copyright (c) 2000-2013 INRIA, France Telecom
Copyright (c) 2004, Eugene Kuleshov
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:
1. Redistributions of source code must retain the above copyright
   notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright
   notice, this list of conditions and the following disclaimer in the
   documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holders nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
THE POSSIBILITY OF SUCH DAMAGE.

Some external libraries that are included with the Annotation Tools have
different licenses.

**Comment by mernst** [comment]
Thanks for pointing out this oversight.
I have added a LICENSE.txt file, licensing the Annotation File Utilities under the MIT License.
The asmx/ directory is a copy of ASM and falls under its license, but we expect to remove the asmx/ directory from the Annotation File Utilities this month.
