### ISSUE TITLE
insert-annotations-to-source does not handle special chars correctly

### ISSUE THREAD

**Issue by pbsf** [typetools/annotation-tools#112]
Consider the following content of a .java class C:

```javascript
public class C {
  public void foo(String orig) {
  }
}
```

Consider the following content of a .jaif file for the class C above:

```javascript
package :
annotation @Key:
    String desc

package :
class C:

    method foo(Ljava/lang/String;)V:
        return:
        parameter #0:
            type: @Key(desc="PartialRegex(\"\\\")")
```

After running 
$ insert-annotations-to-source C.java C.jaif
the annotated C.java will have the following content:

```javascript
public class C {
  public void foo(@Key(desc="PartialRegex("\")") String orig) {
  }
}
```

Note that the annotated C.java contains a compilation error due to the missing backlashes before the second and third double quotation marks, even though they exist on the .jaif file. 

I'm attaching the files used on this example.
[special-chars-bug.zip](https://github.com/typetools/annotation-tools/files/96028/special-chars-bug.zip)

**Comment by mernst** [comment]
The solution seems to be to add quoting back in when inserting (or never have removed it, maybe?).
