### ISSUE TITLE
Projects should use appropriate package names

### ISSUE THREAD

**Issue by wmdietl** [typetools/annotation-tools#121]
At the moment the sub-projects use very short package names, e.g. `type` and `annotations`.
As the AFU are now included in the Checker Framework release, it would be much nicer if AFU used appropriate package names.

**Comment by wmdietl** [comment]
https://github.com/typetools/annotation-tools/pull/147 solved this.

**Comment by mernst** [comment]
The package names still don't conform to Java standards, which would require reverse domain names such as "org.checkerframework.scenelib", but at least the current versions are less confusing than before.
