### ISSUE TITLE
Wrong full qualified name of Enum class

### ISSUE THREAD

**Issue by CharlesZ-Chen** [typetools/annotation-tools#124]
`insert-annotation-to-source` would insert a wrong full qualified name of Enum class when I have a top-level Enum class that holds enum constants of an annotation:

---

test case:
- default.jaif:

``` jaif
package fakeChecker.qual:
  annotation @Annotation:
    enum EnumClass[] values

package :
class Test:
method test()V:
insert-annotation Method.body, Block.statement 0, Variable.type: @fakeChecker.qual.Annotation(values={fakeChecker.qual.EnumClass.ENUM_CONSTANT})
```
- java file:

``` java
public class Test {
    void test() {
        int i = 1;
    }
}
```
- result:

``` java
import fakeChecker.qual.Annotation;
public class Test {
    void test() {
        @Annotation(values={EnumClass.fakeChecker.qual.EnumClass.ENUM_CONSTANT})
        int i = 1;
    }
}
```

In the result, the full qualified name of the `EnumClass` should be `fakeChecker.qual.EnumClass.ENUM_CONSTANT`, but it was inserted as `EnumClass.fakeChecker.qual.EnumClass.ENUM_CONSTANT`, which cause the inserted source code cannot be compiled.

Does anyone could have a possible solution of this?

Thanks!

**Comment by wmdietl** [comment]
Fixed by https://github.com/typetools/annotation-tools/pull/137
