### ISSUE TITLE
Incorrect test setup

### ISSUE THREAD

**Issue by wmdietl** [typetools/annotation-tools#125]
The ad-hoc tests in

https://github.com/typetools/annotation-tools/blob/master/annotation-file-utilities/tests/ad-hoc/bridge/Makefile

don't use the correct version of extract-annotations from the current repository.
Also note that the Makefile uses javac directly, whereas all other Makefiles use the JAVAC variable, which might point to something else.

Another issue that was hiding this configuration error:

https://github.com/typetools/annotation-tools/blob/master/annotation-file-utilities/tests/Makefile#L43

Ignores errors in the sub-Makefiles.
We should ensure that all sub-directories correctly pass and fail on any error.

**Comment by mernst** [comment]
Fixed by commits cdbeb32 and 46e9b21
