### ISSUE TITLE
Can the asmx sub-project be removed?

### ISSUE THREAD

**Issue by wmdietlGC** [typetools/annotation-tools#132]
https://github.com/typetools/annotation-tools/commit/55989dc145586ca13e124d5d0ca85915a18f29e7

sounds like annotation-file-utilities/lib/asm-5.0.jar is now used instead of the asmx sub-project.

Can the asmx sub-project be removed? If not, what is stopping us from doing this?

I see there is a "asm5-final" branch that contains unmerged changes. Are these changes related?

**Comment by mernst** [comment]
There are still a few differences that need to be investigated, after which asmx can be eliminated for good.

**Comment by wmdietlGC** [comment]
Can we remove annotation-file-utilities/lib/asm-5.0.jar then? The asm5-final branch contains a newer jar file and it duplicates the code in the asmx project.

In a similar vein, we currently have a 12MB annotation-file-utilities/lib/plume.jar checked in.
The only part that AFU needs is the "core" of plume, the java code actually contained in plume-lib. All the external libraries are just baggage that is not needed.
I would like to change plume-lib to generate a plume-core.jar or some such that only contains that logic.
This would reduce the external dependencies that are redistributed with AFU.

(We might need a checker-qual.jar, which is currently also included in plume.jar. Making that explicit will greatly improve consistency between the projects.)

**Comment by cushon** [comment]
Is this still in progress? It would be nice to avoid the possibility of version conflicts with other copies of ASM that may be on the classpath. If it could be some time before asmx is removed, consider using a different java package (related: https://github.com/typetools/checker-framework/issues/1819).

**Comment by cushon** [comment]
Friendly ping :) This causes version conflicts when using the annotations tools as a library.

**Comment by cushon** [comment]
Using a different package name for asmx would also avoid version conflicts, and should be an easier change.

**Comment by mernst** [comment]
I made that change in https://github.com/typetools/annotation-tools/pull/177/commits/ea96e8e3a012494517dbddfb059ed0868b134e4c (but it's a digression from the real point of this pull request, https://github.com/typetools/annotation-tools/issues/132).

**Comment by markro49** [comment]
Pull requests https://github.com/typetools/annotation-tools/pull/340  and https://github.com/typetools/checker-framework/pull/4155 removed asmx from the Annotation File Utilities in favor of the official released version of ASM.
