### ISSUE TITLE
Inserted annotation formatted incorrectly for nested annotations

### ISSUE THREAD

**Issue by jyluo** [typetools/annotation-tools#156]
I'm trying to use AFU to insert annotations that have nested annotations. AFU does not format nested annotations correctly when inserting into source code.

Given `default.jaif` file definition:
```
package qual:
  annotation @Inner:
    int number
    String text

package qual:
  annotation @Outer:
    annotation-field qual.Inner[] innerArray

package :
class Variables:

method Main()V:
insert-annotation Method.body, Block.statement 0, Variable.type: @qual.Inner(text="m", number=0)
insert-annotation Method.body, Block.statement 1, Variable.type: @qual.Outer(innerArray={@qual.Inner(text="m", number=0), @qual.Inner(text="s", number=0)})
```

and source file `Variables.java`:
```
class Variables {
    public void Main() {
        int x = 10;
        int y = 20;
    }
}
```

with command:
```
$AFU/scripts/insert-annotations-to-source default.jaif Variables.java
```

the current output is:
```
import qual.Inner;
import qual.Outer;
class Variables {
    public void Main() {
        @Inner(text="m", number=0)
        int x = 10;
        @Outer(innerArray={@qual.Inner({text=m, number=0}),@qual.Inner({text=s, number=0})})
        int y = 20;
    }
}
```

in particular, the nested annotations within `@Outer` have incorrect formatting, ie
```
@Outer(innerArray={@qual.Inner({text=m, number=0}),@qual.Inner({text=s, number=0})})
```
should instead be
```
@Outer(innerArray={@Inner(text="m", number=0), @Inner(text="s", number=0)})
```
Here I expect the nested annotation to be declared via its simple name `Inner` rather than canonical name, and the components of the nested annotation inserted correctly.

As a related issue, the inner annotations do not appear in the imports in the file if the inner annotation was not directly inserted by itself into source (in the given jaif file for variable x).

**Comment by wmdietl** [comment]
@jyluo #162 should fix this issue.
Getting imports for inner annotations is a bit tricky. As inner annotations are currently fully qualified, that shouldn't be a correctness issue.
Give it a spin and let me know whether this works.

**Comment by jyluo** [comment]
Works correctly. Thanks!
