### ISSUE TITLE
ATypeElementTypeWithType returns wrong values

### ISSUE THREAD

**Issue by gsaga** [typetools/annotation-tools#168]
Here's a minimal example:
Note: you'll need to make the constructor `ATypeElementWithType(Object o)` public in order for this to work, just for the test case.

    import scenelib.annotations.el.*;
    import scenelib.type.*;
    
    public class TestEquals {
        public static void main (String[] args) throws Exception {
            ATypeElementWithType e = new ATypeElementWithType("hello");
            ATypeElementWithType a = e.clone();
            a.setType( new ArrayType(new DeclaredType("hello")));
            e.setType( new DeclaredType("hello"));
            System.out.println(a.equals(e));
        }
    }

This will print `true`. This pull request fixes the issue: https://github.com/typetools/annotation-tools/pull/167

**Comment by mernst** [comment]
Could you make this into a unit test that can be run in an automated way?
I suggest adding a new directory under `annotation-tools/scene-lib/test` for unit tests like this.

**Comment by gsaga** [comment]
Updated the pull request with proposed changes and some fixes. I couldn't reply earlier because I wasn't reveiving notifications for comments on issues.
