### ISSUE TITLE
broken link to 3.8.2 release

### ISSUE THREAD

**Issue by cushon** [typetools/annotation-tools#183]
http://checker-framework.org links to https://checkerframework.org/annotation-file-utilities/annotation-tools-3.8.2.zip, which doesn't seem to exist.

https://checkerframework.org/annotation-file-utilities/ still shows the 3.8.1 release.

**Comment by mernst** [comment]
Thanks for pointing this out, and my apologies.
The release process failed partway through.
For now, I have changed the link at http://checker-framework.org to refer to the 3.8.1 release.
