### ISSUE TITLE
insert-annotations-to-source Could not load class

### ISSUE THREAD

**Issue by jerrymatjila** [typetools/annotation-tools#322]
Given java source
``` java
package com.localhost;
public class Test {
    private java.time.LocalDateTime creationDate;
}
```

with goal
``` java
package com.localhost;
public class Test {
    @JsonDeserialize(using = com.example.LocalDateTimeFromEpochDeserializer.class)
    private java.time.LocalDateTime creationDate;
}
```

and jaif file
``` java
package com.fasterxml.jackson.databind.annotation:
annotation @JsonDeserialize: @Retention(value=RUNTIME) @java.lang.annotation.Target(value={TYPE_USE})
    Class using

package com.localhost:
class Test:
    field creationDate: @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = com.example.LocalDateTimeFromEpochDeserializer.class)
```

Parsing error ```org.plumelib.util.FileIOException``` is thrown with message ```Could not load class: com.example.LocalDateTimeFromEpochDeserializer```. This occurs when using 3.9.13 ```insert-annotations-to-source tool```.

How to fix this error?

**Comment by mernst** [comment]
I'm sorry you are having trouble.  I didn't get this error.  But, maybe I ran a different command than you did.

Can you please provide a complete reproduction?  That includes the exact commands you ran on the command line.  That will enable us to reproduce the problem and to help you.  Thanks.

**Comment by jerrymatjila** [comment]
Thanks for a quick response. I have updated jaif file of my original question to include the field that should be modified.

Here are the steps to reproduce the error:

Create Test.java file with following contents
```java
package com.localhost;

public class Test {
    private java.time.LocalDateTime creationDate;
}
```
Create codegen.jaif file with the following contents
```java
package com.fasterxml.jackson.databind.annotation:
annotation @JsonDeserialize: @Retention(value=RUNTIME) @java.lang.annotation.Target(value={TYPE_USE})
    Class using
    
package com.localhost:
class Test:
    field creationDate: @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = com.example.LocalDateTimeFromEpochDeserializer.class)
```

Working directory will now contain 2 files, namely;
```bash
$ tree
.
├── codegen.jaif
└── Test.java
```

Error is observed when executing ```insert-annotations-to-source``` as follows
```bash
$ insert-annotations-to-source codegen.jaif Test.java
Error while parsing annotation file codegen.jaif at line 7:
org.plumelib.util.FileIOException in file codegen.jaif at line 6
Could not load class: com.example.LocalDateTimeFromEpochDeserializer
```

It came to my attention that when changing ```com.example.LocalDateTimeFromEpochDeserializer.class``` to ```java.lang.Object.class``` the command line executes successfully. Therefore somehow ```insert-annotations-to-source``` needs to be aware of  ```com.example.LocalDateTimeFromEpochDeserializer``` class. ```LocalDateTimeFromEpochDeserializer``` can exist in a different jar file or classpath. I do not know how to resolve this.

**Comment by mernst** [comment]
Thank you for the reproduction.  Your observation that `LocalDateTimeFromEpochDeserializer` needs to be on the classpath is correct.

I think your bug report exposes two problems:
 * the manual is not clear about what needs to be on the classpath
 * the error message does not say how to fix the problem (namely, put the class on the classpath)

I have opened pull request #324 to address this.  Let me know if you have comments on it.

> `LocalDateTimeFromEpochDeserializer` can exist in a different jar file or classpath. I do not know how to resolve this.

You can pass the `-cp` or `-classpath` command-line argument to `insert-annotations-to-source`.
Or, you can set the `CLASSPATH` environment variable before calling `insert-annotations-to-source`, as in:
```
(CLASSPATH=my.jar && insert-annotations-to-source ...)
```
Does that answer your question?

**Comment by jerrymatjila** [comment]
From your suggested solutions, I tried ```CLASSPATH``` and it worked! Thanks.

**Comment by mernst** [comment]
I'm glad that worked.  I have also improved the diagnostic messages and the manual, so hopefully others will not have this problem.  Thanks again for the bug report.
